// CandidateFieldEnum.ts
export const CandidateTableHeaderEnum = {
  CandidateName: 'Họ tên',
  Mobile: 'Số điện thoại',
  Email: 'Email',
  RecruitmentCampaignNames: 'Chiến dịch tuyển dụng',
  JobPositionName: 'Vị trí tuyển dụng',
  RecruitmentRoundName: 'Vòng tuyển dụng',
  Score: 'Đánh giá',
  ApplyDate: 'Ngày ứng tuyển',
  ChannelName: 'Nguồn ứng viên',
  EducationDegreeName: 'Trình độ đào tạo',
  EducationPlaceName: 'Nơi đào tạo',
  EducationMajorName: 'Chuyên ngành',
  WorkPlaceRecent: 'Nơi làm việc gần đây nhất',
  AttractivePersonnel: 'Nhân sự khai thác',
  OrganizationUnitName: 'Đơn vị sử dụng',
  Overall: 'Phù hợp với chân dung',
  AreaName: 'Khu vực',
  PresenterName: 'Người giới thiệu',
  ProbationInfoStatus: 'Thông tin tiếp nhận',
  IsTalentPoolDetail: 'Thuộc kho tiềm năng',
  AccountPortal: 'Tài khoản cổng ứng viên',
  TagInfos: 'Thẻ',
  CandidateStatusName: 'Trạng thái',
  Gender: 'Giới tính',
  Birthday: 'Ngày sinh',
  Address: 'Địa chỉ',
  ReasonRemoved: 'Lý do loại',
  CollaboratorName: 'Cộng tác viên',
  HireDate: 'Ngày tiếp nhận',
  OfferStatus: 'Trạng thái mời nhận việc',
}
